// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/health": {
            "get": {
                "description": "Vérifie que le serveur est en ligne",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "health"
                ],
                "summary": "Status du serveur",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.HealthResult"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/all": {
            "get": {
                "description": "Lance les 5 scanners en parallèle via goroutines",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "All Scan",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api.ScanResult"
                            }
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/dns": {
            "get": {
                "description": "Analyse les records DNS du domaine (A, AAAA, MX, NS, TXT)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "Scan DNS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResult"
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/header": {
            "get": {
                "description": "Vérifie les headers de sécurité (HSTS, CSP, X-Frame-Options, X-Content-Type-Options)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "Scan Headers HTTP",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResult"
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/sensitive": {
            "get": {
                "description": "Détecte les fichiers sensibles exposés (.env, .git/config, wp-config.php, etc.)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "Scan fichiers sensibles",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResult"
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/ssl": {
            "get": {
                "description": "Analyse le certificat TLS du domaine (émetteur, expiration, validité)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "Scan SSL/TLS",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResult"
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/scan/subdomain": {
            "get": {
                "description": "Énumère les sous-domaines via Certificate Transparency (crt.sh)",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "scanner"
                ],
                "summary": "Scan sous-domaines",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Domaine à scanner",
                        "name": "domain",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api.ScanResult"
                        }
                    },
                    "400": {
                        "description": "paramètre 'domain' requis",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "erreur serveur",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api.HealthResult": {
            "type": "object",
            "properties": {
                "status": {
                    "type": "string"
                }
            }
        },
        "api.ScanResult": {
            "type": "object",
            "properties": {
                "domain": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "scanner": {
                    "type": "string"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8082",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "GoSentry — Security Audit API",
	Description:      "API d'audit de surface d'attaque externe. Analyse DNS, certificats SSL/TLS, headers de sécurité, sous-domaines et fichiers sensibles exposés.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
